### ISSUE TITLE
Falta un link en la home al blog de Humitos

### ISSUE THREAD

**Issue by jjconti** [humitos/argentinaenpython.com.ar#1]
Me parece que falta un link en el home de argentinaenpython.com.ar a elblogdehumitos.com.ar. Llegué desde el segundo al primero y luego "no pude volver".

**Comment by humitos** [comment]
Interesante.

En el menú "Extras" hay un link que se llama "Blog" y apunta a la 
catergoría "Argentina en Python" de elblogdehumitos.com.ar

¿No es suficiente con eso?

¿Dónde pondrías el link a elblogdehumitos.com.ar en el Home de 
argentinaenpython.com.ar?

¿Me ayudás?

-- 

Kaufmann Manuel
-- http://elblogdehumitos.com.ar/

**Comment by jjconti** [comment]
DMMT, nunca lo encontré ahi. Lo podría en el Manuel Kaufmann del pie.

El 10 de junio de 2015, 14:46, Manuel Kaufmann <notifications@github.com>
escribió:

> Interesante.
>
> En el menú "Extras" hay un link que se llama "Blog" y apunta a la
> catergoría "Argentina en Python" de elblogdehumitos.com.ar
>
> ¿No es suficiente con eso?
>
> ¿Dónde pondrías el link a elblogdehumitos.com.ar en el Home de
> argentinaenpython.com.ar?
>
> ¿Me ayudás?
>
> --
>
> Kaufmann Manuel
> -- http://elblogdehumitos.com.ar/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/humitos/argentinaenpython.com.ar/issues/1#issuecomment-110849768>
> .
>



-- 
Juanjo Conti
Mi primer novela ya se puede conseguir en:
http://www.juanjoconti.com.ar/xolopes

**Comment by humitos** [comment]
Hecho. Gracias por el reporte.
